apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plantuml
  labels:
    app: plantuml
    tier: backend
  namespace: crowi
spec:
  replicas: 1
  template:
    metadata:
      name: plantuml
      labels:
        app: plantuml
        tier: backend
    spec:
      containers:
        - name: plantuml
          image: plantuml/plantuml-server:latest
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: elm
