apiVersion: v1
kind: Service
metadata:
  name: plantuml
  namespace: crowi
spec:
  type: ClusterIP
  selector:
    app: plantuml
  ports:
    - name: http
      port: 18080
      targetPort: 8080
  externalIPs:
    - 10.0.3.102
