apiVersion: v1
kind: Service
metadata:
  name: http-https-proxy
  namespace: crowi
spec:
  type: ClusterIP
  selector:
    app: http-https-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  externalIPs:
    - 10.0.3.102
