version: '3'

services:
  crowi:
    build: crowi
    # image: 10.0.3.1:5000/crowi/crowi:1.6.2
    ports:
      - 8080:3000
    volumes:
      - /var/local/kubernetes/pv/crowi/uploads:/opt/crowi/public/uploads
    environment:
      - DEBUG="false"
      - MONGO_SERVICE_HOST=mongo
      - REDIS_SERVICE_HOST=redis
      - ELASTICSEARCH_SERVICE_HOST=elasticsearch
      - PASSWORD_SEED=kutreHEwEwaprEsP7f82taTr
      - SECRET_TOKEN=qesajUvarayUWruqenEkac4a
      - MATHJAX="0"
      - PLANTUML_URI=http://10.0.3.102:18080

  mongo:
    image: mongo:latest
    volumes:
      - /var/local/kubernetes/pv/crowi/db:/data/db

  redis:
    image: redis:latest

  elasticsearch:
    build: elasticsearch
    # image: 10.0.3.1:5000/crowi/crowi-es:5

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - 18081:8080
